/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb20232.ventanas;

import co.edu.unicolombo.pb20232.Saldos;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Maldonado
 */


public class Masculino extends javax.swing.JFrame {
    int juego = 0;
    int saldoinicial = 1000;
   Random random = new Random();
   Saldos operar = new Saldos();
   
   public DefaultTableModel modelo;
   
  
    public Masculino() {
     
        initComponents();
         modelo= new DefaultTableModel();
        modelo.addColumn("Nombre del equipo ");
        modelo.addColumn("Sedes");
        modelo.addColumn("Tipo de juego ");
        modelo.addColumn("Propietario");
        modelo.addColumn("PJ");
        modelo.addColumn("PG");
        modelo.addColumn("PP");
        modelo.addColumn("P");
       
        agregarEquipo("Rusia","Mosku","Masculino","Yuri Marichev");
        agregarEquipo2("Japon","Tokio","Masculino","Hirofumi Daimatsu");       
        agregarEquipo3("Argentina","Buenos Aires","Masculino","Marcelo Méndez");
        agregarEquipo4("Polonia","Varsovia","Masculino"," Nikola Grbić");
        agregarEquipo5("Estados Unidos","Washintong","Masculino","John Speraw");
        
         
        
        
       
        
        
        
        
        this.tabla.setModel(modelo);
         saldo.setText(String.valueOf(saldoinicial));
        int saldoo = Integer.parseInt(saldo.getText());
        if (saldoo>0){
             saldo.setForeground(Color.GREEN);
        } else {
             saldo.setForeground(Color.RED);
        }
    }
private void agregarEquipo(String nombreEquipo1, String sedeequipo1, String masculino, String propietario) {
        Object[] fila = {nombreEquipo1,sedeequipo1,masculino,propietario,0, 0, 0, 0};
        modelo.addRow(fila);
    }

private void agregarEquipo2(String nombreEquipo1, String sedeequipo1, String masculino, String yuri_Marichev) {
        Object[] fila = {nombreEquipo1,sedeequipo1,masculino,yuri_Marichev,0, 0, 0, 0};
        modelo.addRow(fila);
    }
private void agregarEquipo3(String nombreEquipo, String sedeequipo, String masculino, String propietario) {
        Object[] fila = {nombreEquipo,sedeequipo,masculino,propietario,0, 0, 0, 0};
        modelo.addRow(fila);
    }
private void agregarEquipo4(String nombreEquipo, String sedeequipo, String masculino, String propietario) {
        Object[] fila = {nombreEquipo,sedeequipo,masculino,propietario,0, 0, 0, 0};
        modelo.addRow(fila);
    }
private void agregarEquipo5(String nombreEquipo, String sedeequipo, String masculino, String propietario) {
        Object[] fila = {nombreEquipo,sedeequipo,masculino,propietario,0, 0, 0, 0};
        modelo.addRow(fila);
    }
   private void agregarEquipo6() {
       

        Object[] fila = {nombredelequipo.getText(), sede.getText(), tipodejuego.getSelectedItem(), propietario.getText(), 0, 0, 0, 0};
        modelo.addRow(fila);
        restarValorDeseado(500);
        
        
                
        if (!nombredelequipo.getText().isEmpty() || !sede.getText().isEmpty() || !propietario.getText().isEmpty()) {
            if (juego == 0) {
                Registrar.setEnabled(false);
                juego = 1;
            }

        }

    }

private void resetearColumnas(DefaultTableModel modelo, int columna) {
        int contador_de_fila = modelo.getRowCount();
        for (int i = 0; i < contador_de_fila; i++) {
            modelo.setValueAt(0, i, columna);
        }
    }

 private void restarValorDeseado(int valor) {
        // Resta el valor deseado de la variable y actualiza el texto del JLabel
        saldoinicial -= valor;
        saldo.setText("" + saldoinicial);
    }
 
 public void sumarValorDeseado(int valor) {
        // Resta el valor deseado de la variable y actualiza el texto del JLabel
        saldoinicial += valor;
        saldo.setText("" + saldoinicial);
    }


 
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombredelequipo = new javax.swing.JTextField();
        Reiniciar = new javax.swing.JButton();
        sede = new javax.swing.JTextField();
        propietario = new javax.swing.JTextField();
        Jugar = new javax.swing.JButton();
        tipodejuego = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Contraseña = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtfila = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcolumna = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();
        txtdatonuevo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        premio = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        recargar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombredelequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombredelequipoActionPerformed(evt);
            }
        });
        jPanel1.add(nombredelequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 224, 20));

        Reiniciar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Reiniciar.setText("Reiniciar");
        Reiniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 255), null, null));
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 118, 40));

        sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedeActionPerformed(evt);
            }
        });
        jPanel1.add(sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 166, 224, -1));

        propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propietarioActionPerformed(evt);
            }
        });
        jPanel1.add(propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 259, 220, -1));

        Jugar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb20232/ventanas/Imagenes/jugador-de-voleibol (1).png"))); // NOI18N
        Jugar.setText("Jugar");
        Jugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 255), null, null));
        Jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JugarMouseClicked(evt);
            }
        });
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        jPanel1.add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 112, 40));

        tipodejuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Masculino" }));
        jPanel1.add(tipodejuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 214, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ingrese contraseña de administrador: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 294, -1, 22));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb20232/ventanas/Imagenes/editar (1).png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 255), null, null));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1036, 374, 134, 46));
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 334, 316, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese La Fila :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 94, -1, 29));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(80, 178, 211));
        jLabel10.setText("Modificar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1036, 51, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Ingrese La Columna :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 154, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Ingrese el dato a reemplazar:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 208, -1, -1));

        txtfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilaActionPerformed(evt);
            }
        });
        jPanel1.add(txtfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 98, 190, -1));

        tabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 29, 646, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 150, 195));
        jLabel1.setText("Registrar equipo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 73, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre del equipo :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sede:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 136, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tipo de juego :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 214, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Propietario :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, 140, -1));
        jPanel1.add(txtcolumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(1246, 154, 172, -1));

        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Registrar.setText("Registrar");
        Registrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 255), null, null));
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
        });
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 359, 110, 40));
        jPanel1.add(txtdatonuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 246, 316, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Saldo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        saldo.setText("0.00");
        jPanel1.add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 21, 30, -1));

        premio.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        premio.setText("Reclamar premio");
        premio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        premio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                premioMouseClicked(evt);
            }
        });
        premio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premioActionPerformed(evt);
            }
        });
        jPanel1.add(premio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, -1, 40));

        jLabel12.setText("$");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 21, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 100, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Eliminar todo");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 110, 40));

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel13.setText("Ingrese el valor a recargar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));
        jPanel1.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 200, -1));

        recargar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        recargar.setText("Recargar");
        recargar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarActionPerformed(evt);
            }
        });
        jPanel1.add(recargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 100, 40));

        jButton1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb20232/ventanas/atras (1).png"))); // NOI18N
        jButton1.setText("Atras");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombredelequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombredelequipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombredelequipoActionPerformed

    private void sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedeActionPerformed

    private void propietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propietarioActionPerformed

    private void JugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JugarMouseClicked
        int filas = modelo.getRowCount();
        boolean equipoGanador = false;  // Variable para rastrear si ya hay un equipo ganador

        for (int i = 0; i < filas; i++) {
            int puntos = (int) modelo.getValueAt(i, 7);

            if (puntos == 13) {
                equipoGanador = true;
                break;  // Termina el bucle si ya hay un equipo ganador
            }
        }

        if (equipoGanador) {
            JOptionPane.showMessageDialog(this, "Un equipo ya ha ganado, Presione el boton reiniciar");
        } else {
            // Verificar otras condiciones después de revisar todas las filas
            if (nombredelequipo.getText().isEmpty() || sede.getText().isEmpty() || propietario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe registrarse primero");
            } else {
                sumarPartidoJugado2();
            }
        }
    }//GEN-LAST:event_JugarMouseClicked

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
      
    }//GEN-LAST:event_JugarActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String contraseña = "123";
        if(Contraseña.getText().equals(contraseña) ){
            int fila=Integer.parseInt(txtfila.getText());

            int columna=Integer.parseInt(txtcolumna.getText());
            if(columna<4){
                String datonuevo = txtdatonuevo.getText();
                modelo.setValueAt(txtdatonuevo.getText(), fila, columna);
            }
            else {
                JOptionPane.showMessageDialog(this, " Los eventos no se pueden modificar ");
            }
        }

        else{
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilaActionPerformed

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
    
    }//GEN-LAST:event_RegistrarMouseClicked

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        if(saldoinicial==0){
             Registrar.setEnabled(true);
             JOptionPane.showMessageDialog(rootPane, "Si gusta en participar, por favor Recargue");
            
        
       } else{
           if (nombredelequipo.getText().isEmpty() || sede.getText().isEmpty()
                || propietario.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Si gusta en participar, por favor complete todos los campos");
        } else {
            agregarEquipo6();
       }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void premioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_premioMouseClicked
       if (nombredelequipo.getText().isEmpty() || sede.getText().isEmpty() || propietario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe registrarse si quiere reclamar");
        } else {
            // Verificar si hay un equipo ganador
            boolean equipoGanadorFila6 = false;

            for (int i = 0; i < modelo.getRowCount(); i++) {
                int puntos = (int) modelo.getValueAt(i, 7);
                if (puntos >= 13 && i == 5) { // Verificar que sea el equipo de la fila 6, columna 7
                    equipoGanadorFila6 = true;
                    break;
                }
            }

            if (!equipoGanadorFila6) {
                JOptionPane.showMessageDialog(this, "Primero debe ganar el equipo de la fila 6 para presionar el botón, presione el boton reiniciar");
            } else {
                int puntosFila6 = (int) modelo.getValueAt(5, 7);

                if (puntosFila6 == 13) {
                    sumarValorDeseado(500);

                    // Eliminar la fila número 5
                    modelo.removeRow(5);
                    if (juego == 1) {
                    juego = 0;
                    Registrar.setEnabled(true);
                    propietario.setText("");
                    nombredelequipo.setText("");
                    sede.setText("");
                    }

                    // Método para establecer los valores de las columnas a cero para todas las filas
                    resetearColumnas(modelo, 4);
                    resetearColumnas(modelo, 5);
                    resetearColumnas(modelo, 6);
                    resetearColumnas(modelo, 7);
                } else {
                    // Mensaje si el valor de la fila 6, columna 7 no es igual a 13
                    JOptionPane.showMessageDialog(this, "El equipo en la fila 6 aún no ha ganado");
                }
            }
       }

       

        
    }//GEN-LAST:event_premioMouseClicked

    private void premioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_premioActionPerformed

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        int filas = modelo.getRowCount();
        boolean equipoGanador = false;  // Variable para rastrear si ya hay un equipo ganador
        int filaEquipoGanador = -1;  // Almacena la fila del equipo ganador, si lo hay

        // Bucle para verificar si hay un equipo ganador
        for (int i = 0; i < filas; i++) {
            int puntos = (int) modelo.getValueAt(i, 7);

            if (puntos >= 13) {
                equipoGanador = true;
                filaEquipoGanador = i;
                // No rompemos el bucle para verificar todas las filas y reiniciar valores en todas
            }
        }

        // Verificar si hay un equipo ganador
        if (equipoGanador) {
            // Reiniciar valores de las columnas a 0 en todas las filas
            int columna_a_seleccionada_4 = 4;
            int columna_a_seleccionada_5 = 5;
            int columna_a_seleccionada_6 = 6;
            int columna_a_seleccionada_7 = 7;

            for (int i = 0; i < filas; i++) {
                modelo.setValueAt(0, i, columna_a_seleccionada_4);
                modelo.setValueAt(0, i, columna_a_seleccionada_5);
                modelo.setValueAt(0, i, columna_a_seleccionada_6);
                modelo.setValueAt(0, i, columna_a_seleccionada_7);
            }

            // Eliminar la fila número 5
            if (filaEquipoGanador < 5) {
                modelo.removeRow(5);
                if (juego == 1) {
                    juego = 0;
                    Registrar.setEnabled(true);
                    propietario.setText("");
                    nombredelequipo.setText("");
                    sede.setText("");

                }
            } else {
                modelo.removeRow(filaEquipoGanador);
            }

            JOptionPane.showMessageDialog(this, "¡Hemos encontrado un ganador!");
        } else {
            // Verificar otras condiciones después de revisar todas las filas

            if (nombredelequipo.getText().isEmpty() || sede.getText().isEmpty() || propietario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe registrarse primero");
            } else {
                JOptionPane.showMessageDialog(this, "Ningún equipo ha ganado aún");

                // Puedes agregar más lógica aquí si es necesario
            }
        }

    }//GEN-LAST:event_ReiniciarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila =tabla.getSelectedRow();
        if(fila>=0){
            modelo.removeRow(fila);

        }else{
            JOptionPane.showMessageDialog(null,"seleccione la fila");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int fila=tabla.getRowCount();
        for (int i=fila-1; i>=0; i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void recargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarActionPerformed
        // TODO add your handling code here:
        if (valor.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Por favor llene el valor a recargar");
        } else{
            int entero = Integer.parseInt(valor.getText());
            sumarValorDeseado(entero);
        }
    }//GEN-LAST:event_recargarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Ligas atrs = new Ligas();
        atrs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
private void sumarPartidoJugado() {
    
    
      //------------------------------------------------------------------------------------------------------------------------------
        
      // partidos jugados
      
      
      
      
      
      int filas = modelo.getRowCount();
        for (int i = 0; i < filas; i++) {
            int partidosJugados = (int) modelo.getValueAt(i, 4);
            modelo.setValueAt(partidosJugados + 1, i, 4);
        }//Cuando se presiona jugar a los partidos jugados se les suma uno
      
       
          //------------------------------------------------------------------------------------------------------------------------------
          
          
          // partidos ganados y perdidos
          
          
          
          
          
         int filas1 = modelo.getRowCount();
        for (int i = 0; i < filas1; i++) {
            double numeroaleatorio = random.nextDouble();
           if(numeroaleatorio < 0.5){
            int partidosGanados = (int) modelo.getValueAt(i, 5);
            modelo.setValueAt(partidosGanados+ 1, i, 5);
           } else {
                int partidosGanados = (int) modelo.getValueAt(i, 6);
                modelo.setValueAt(partidosGanados+ 1, i, 6);
           }
        }// Cuando se presiona jugar hay un 50% de probabilidad de que gane un partido
        
        //------------------------------------------------------------------------------------------------------------------------------
        
       
        
        
        
        
        
        
        
        
        //Sistema de puntos
        
        
          
            int partidosGanados1 = (int) modelo.getValueAt(0, 5);
           if( partidosGanados1 == 1 || partidosGanados1 == 2 || partidosGanados1 == 10 || partidosGanados1 == 3 || partidosGanados1 == 4 || partidosGanados1 == 5 || partidosGanados1 == 6 || partidosGanados1 == 7 || partidosGanados1 == 8 || partidosGanados1 == 9  ){
            modelo.setValueAt(partidosGanados1 + 3, 0, 7);// hago que le sume puntos a la columna de puntos
           }
        
           
            int partidosGanados2 = (int) modelo.getValueAt(1, 5);
           if( partidosGanados2 == 1 || partidosGanados2 == 2 || partidosGanados2 == 3 || partidosGanados2 == 4 || partidosGanados2 == 5 || partidosGanados2 == 6 || partidosGanados2 == 7 || partidosGanados2 == 8 || partidosGanados2 == 9 || partidosGanados2 == 10  ){
            modelo.setValueAt(partidosGanados2 + 3, 1, 7);
           }
        
            
            int partidosGanados3 = (int) modelo.getValueAt(2, 5);
           if(  partidosGanados3 == 1 || partidosGanados3 == 2 || partidosGanados3 == 3 || partidosGanados3 == 4 || partidosGanados3 == 5 || partidosGanados3 == 6 || partidosGanados3 == 7 || partidosGanados3 == 8 || partidosGanados3 == 9 || partidosGanados3 == 10  ){
            modelo.setValueAt(partidosGanados3 + 3, 2, 7);// hago que le sume puntos a la columna de puntos
           }
        
            
            int partidosGanados4 = (int) modelo.getValueAt(3, 5);
           if( partidosGanados4 == 1 || partidosGanados4 == 2 || partidosGanados4 == 3 || partidosGanados4 == 4 || partidosGanados4 == 5 || partidosGanados4 == 6 || partidosGanados4 == 7 || partidosGanados4 == 8 || partidosGanados4 == 9 || partidosGanados4 == 10 ){
            modelo.setValueAt(partidosGanados4 + 3, 3, 7);// hago que le sume puntos a la columna de puntos
           
        }
            
            int partidosGanados5 = (int) modelo.getValueAt(4, 5);
           if( partidosGanados5 == 1 || partidosGanados5 == 2 || partidosGanados5 == 3 || partidosGanados5 == 4 || partidosGanados5 == 5 || partidosGanados5 == 6 || partidosGanados5 == 7 || partidosGanados5 == 8 || partidosGanados5 == 9 || partidosGanados5 == 10 ){
            modelo.setValueAt(partidosGanados5 + 3, 4, 7);// hago que le sume puntos a la columna de puntos
           
        }
              
          
        
              
        
              
              //---------------------------------------------------------------------------------------------------------------------------------------
              
              
              //Sitema de ganador
              
             
            int puntos1 = (int) modelo.getValueAt(0, 7);
           if( puntos1 == 13  ){
            JOptionPane.showMessageDialog(this, " El equipo 1 ha ganado ");
           }
        
           
            int puntos2 = (int) modelo.getValueAt(1, 7);
           if( puntos2 == 13  ){
           JOptionPane.showMessageDialog(this, " El equipo 2 ha ganado ");
           }
        
           
            int puntos3 = (int) modelo.getValueAt(2, 7);
           if(  puntos3 == 13   ){
          JOptionPane.showMessageDialog(this, " El equipo 3 ha ganado ");
           }
        
            
            int puntos4 = (int) modelo.getValueAt(3, 7);
           if( puntos4 == 13 ){
           JOptionPane.showMessageDialog(this, " El equipo 4 ha ganado ");
           }
        
            
            int puntos5 = (int) modelo.getValueAt(4, 7);
           if( puntos5 == 13 ){
            JOptionPane.showMessageDialog(this, " El equipo numero 5 ha ganado ");
           }
        
             
           
        
              
              //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              
              
              
              
              
              
              
    }

private void sumarPartidoJugado2() {
    
    
      //------------------------------------------------------------------------------------------------------------------------------
        
      // partidos jugados
      
      
      
      
      
      int filas = modelo.getRowCount();
        for (int i = 0; i < filas; i++) {
            int partidosJugados = (int) modelo.getValueAt(i, 4);
            modelo.setValueAt(partidosJugados + 1, i, 4);
        }//Cuando se presiona jugar a los partidos jugados se les suma uno
      
       
          //------------------------------------------------------------------------------------------------------------------------------
          
          
          // partidos ganados y perdidos
          
          
          
          
          
         int filas1 = modelo.getRowCount();
        for (int i = 0; i < filas1; i++) {
            double numeroaleatorio = random.nextDouble();
           if(numeroaleatorio < 0.5){
            int partidosGanados = (int) modelo.getValueAt(i, 5);
            modelo.setValueAt(partidosGanados+ 1, i, 5);
           } else {
                int partidosGanados = (int) modelo.getValueAt(i, 6);
                modelo.setValueAt(partidosGanados+ 1, i, 6);
           }
        }// Cuando se presiona jugar hay un 50% de probabilidad de que gane un partido
        
        //------------------------------------------------------------------------------------------------------------------------------
        
       
        
        
        
        
        
        
        
        
        //Sistema de puntos
        
        
          
            int partidosGanados1 = (int) modelo.getValueAt(0, 5);
           if( partidosGanados1 == 1 || partidosGanados1 == 2 || partidosGanados1 == 10 || partidosGanados1 == 3 || partidosGanados1 == 4 || partidosGanados1 == 5 || partidosGanados1 == 6 || partidosGanados1 == 7 || partidosGanados1 == 8 || partidosGanados1 == 9  ){
            modelo.setValueAt(partidosGanados1 + 3, 0, 7);// hago que le sume puntos a la columna de puntos
           }
        
           
            int partidosGanados2 = (int) modelo.getValueAt(1, 5);
           if( partidosGanados2 == 1 || partidosGanados2 == 2 || partidosGanados2 == 3 || partidosGanados2 == 4 || partidosGanados2 == 5 || partidosGanados2 == 6 || partidosGanados2 == 7 || partidosGanados2 == 8 || partidosGanados2 == 9 || partidosGanados2 == 10  ){
            modelo.setValueAt(partidosGanados2 + 3, 1, 7);
           }
        
            
            int partidosGanados3 = (int) modelo.getValueAt(2, 5);
           if(  partidosGanados3 == 1 || partidosGanados3 == 2 || partidosGanados3 == 3 || partidosGanados3 == 4 || partidosGanados3 == 5 || partidosGanados3 == 6 || partidosGanados3 == 7 || partidosGanados3 == 8 || partidosGanados3 == 9 || partidosGanados3 == 10  ){
            modelo.setValueAt(partidosGanados3 + 3, 2, 7);// hago que le sume puntos a la columna de puntos
           }
        
            
            int partidosGanados4 = (int) modelo.getValueAt(3, 5);
           if( partidosGanados4 == 1 || partidosGanados4 == 2 || partidosGanados4 == 3 || partidosGanados4 == 4 || partidosGanados4 == 5 || partidosGanados4 == 6 || partidosGanados4 == 7 || partidosGanados4 == 8 || partidosGanados4 == 9 || partidosGanados4 == 10 ){
            modelo.setValueAt(partidosGanados4 + 3, 3, 7);// hago que le sume puntos a la columna de puntos
           
        }
            
            int partidosGanados5 = (int) modelo.getValueAt(4, 5);
           if( partidosGanados5 == 1 || partidosGanados5 == 2 || partidosGanados5 == 3 || partidosGanados5 == 4 || partidosGanados5 == 5 || partidosGanados5 == 6 || partidosGanados5 == 7 || partidosGanados5 == 8 || partidosGanados5 == 9 || partidosGanados5 == 10 ){
            modelo.setValueAt(partidosGanados5 + 3, 4, 7);// hago que le sume puntos a la columna de puntos
           
        }
              
            int partidosGanados = (int) modelo.getValueAt(5, 5);
           if( partidosGanados == 1 || partidosGanados == 2 || partidosGanados == 3 || partidosGanados == 4 || partidosGanados == 5 || partidosGanados == 6 || partidosGanados == 7 || partidosGanados == 8 || partidosGanados == 9 || partidosGanados == 10 ){
            modelo.setValueAt(partidosGanados + 3, 5, 7);// hago que le sume puntos a la columna de puntos
           }
        
              
        
              
              //---------------------------------------------------------------------------------------------------------------------------------------
              
              
              //Sitema de ganador
              
             
            int puntos1 = (int) modelo.getValueAt(0, 7);
           if( puntos1 == 13  ){
            JOptionPane.showMessageDialog(this, " El equipo 1 ha ganado ");
           }
        
           
            int puntos2 = (int) modelo.getValueAt(1, 7);
           if( puntos2 == 13  ){
           JOptionPane.showMessageDialog(this, " El equipo 2 ha ganado ");
           }
        
           
            int puntos3 = (int) modelo.getValueAt(2, 7);
           if(  puntos3 == 13   ){
          JOptionPane.showMessageDialog(this, " El equipo 3 ha ganado ");
           }
        
            
            int puntos4 = (int) modelo.getValueAt(3, 7);
           if( puntos4 == 13 ){
           JOptionPane.showMessageDialog(this, " El equipo 4 ha ganado ");
           }
        
            
            int puntos5 = (int) modelo.getValueAt(4, 7);
           if( puntos5 == 13 ){
            JOptionPane.showMessageDialog(this, " El equipo numero 5 ha ganado ");
           }
        
             
            int puntos = (int) modelo.getValueAt(5, 7);
           if( puntos == 13 ){
            JOptionPane.showMessageDialog(this, " El equipo numero 6 ha ganado ");
           }
        
              
              //---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              
              
              
              
              
              
              
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masculino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contraseña;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombredelequipo;
    private javax.swing.JButton premio;
    private javax.swing.JTextField propietario;
    private javax.swing.JButton recargar;
    private javax.swing.JLabel saldo;
    private javax.swing.JTextField sede;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipodejuego;
    private javax.swing.JTextField txtcolumna;
    private javax.swing.JTextField txtdatonuevo;
    private javax.swing.JTextField txtfila;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}